### ISSUE TITLE
你好! 有个问题帮解决下!

### ISSUE THREAD

**Issue by liule024** [alexqu0822/alaTradeSkill#1]
安装alaTradeSkill 后,在weakauras2的 颜色选择器 里会出现 横板的透明度选项,点了没有用, 还遮挡视野!
麻烦修复下! 感谢!
![asr](https://user-images.githubusercontent.com/70201394/93260091-77e6dc80-f7d3-11ea-8ff2-a579db7db1ac.jpg)

**Comment by alexqu0822** [comment]
这个问题应该已经解决了
