### ISSUE TITLE
Compatibility for Auctipus

### ISSUE THREAD

**Issue by tanrak** [alexqu0822/alaTradeSkill#4]
There is a new auction house addon named [Auctipus](https://github.com/empiricalbw/Auctipus). Is it possible to make this compatible to alaTradeSkill as well?

**Comment by alexqu0822** [comment]
woh, a new auction addon. 
I will test it out and support its data.

**Comment by alexqu0822** [comment]
The latest files on curseforge support auctipus now.

**Comment by tanrak** [comment]
I see, Many thanks!
